<div class="z-footer clearfix">
    <div class="z-col-four">
        <ul class="z-col">
            <h3>Business Info</h3>
            <li>Takes Reservations - Yes</li>
            <li>Delivery - Yes</li>
            <li>Take Away - Yes</li>
            <li>Accepted Cards - Credit, Debit</li>
            <li>Parking - Private Lot</li>
            <li>Good for Kids - Yes</li>
            <li>Good for Groups - Yes</li>
            <li>Attire - Casual</li>
            <li>Ambience - Casual</li>
            <li>Noise - Level Average</li>
            <li>Wi-Fi - Yes</li>
            <li>Caters - Yes</li>
        </ul>
    </div>                

    <div class="z-col-four">
        <ul class="z-col">
            <h3>Opening Hours</h3>
            <li>Sun 3:00 PM - 10:00 PM</li>
            <li>Mon 3:00 PM - 10:00 PM</li>
            <li>Tue 3:00 PM - 10:00 PM</li>
            <li>Wed 3:00 PM - 10:00 PM</li>
            <li>Thu 3:00 PM - 10:00 PM</li>
            <li>Fri 3:00 PM - 11:30 PM</li>
            <li>Sat 3:00 PM - 11:30 PM</li>
        </ul>
    </div>                

    <div class="z-col-four z-last">
        <ul class="z-col">
            <h3>Our Locations</h3>
            <li>4771 Cane Run Road</li>
            <li>Louisville, KY 40216 </li>
            <li class="z-social-break">Call (502) 449-4444</li>
            <h3>Follow Us</h3>
            <li class="z-social-i"><a href="https://www.tripadvisor.com/Restaurant_Review-g39604-d9862412-Reviews-Annie_s_Pizza-Louisville_Kentucky.html"><i class="fa fa-tripadvisor"></i></a></li>
            <li class="z-social-i"><a href="https://www.facebook.com/pages/category/Pizza-Place/Annies-Pizza-341873682552370/"><i class="z-icon icon-facebook-1"></i></a></li>
            <li class="z-social-i"><a href="https://www.yelp.com/biz/annies-pizza-louisville-3"><i class="z-icon icon-yelp-1"></i></a></li>
        </ul>
    </div>
</div><!-- #footer -->

<div class="z-copyright">
    <p>Website and online ordering by <a href="http://bigholler.com/" target="_blank">BigHoller – Food at your Fingertips</a></p>
</div><!-- #copyright -->