<div class="z-testimonial">
	<h3>What Our Customers Say</h3>
    <p>Annie's Pizza has been a staple in Louisville since I was a small child. Not much has changed aside from the employees. The pizza is delicious and the employees are all very friendly and helpful. The price is slightly higher than your normal pizza place, but I'm happy to pay the difference considering the overall experience is always a great one. The restaurant is always clean. The restrooms are always in order and clean as well. Delivery time can be somewhat lengthy, however the last order I made for delivery ran a bit late and the delivery person compensated me with a coupon for a free personal size pizza with my next purchase. I would recommend Annie's Pizza to anyone looking for a good pizza.</p>
    <span>- Trina Duke, via Google</span>
    <p>&nbsp;</p>
    <p>Annie’s pizza has not let me down once yet. I have been about a dozen times in the past 3 or so years. It has a sauce that is very appealing and sets it apart from the other places. If you ever want to be amazed get their largest pizza. They will ask how wide the doorway is where it’s being delivered, that’s so they know if it will fit through it. When you get it and raise the lid its feels like you are lifting your car hood up. 😀 give em a try I think you will like their pizza. I haven’t tried anything else there but the pizza.</p>
    <span>- smplsimonsays, via Google</span>
	<p>&nbsp;</p>
	<img src="img/image1.png" />
</div><!-- #testimonial -->